### ISSUE TITLE
User-defined mo_coeff not stored in CASSCF or CASCI object?

### ISSUE THREAD

**Issue by wirawan0** [sunqm/pyscf#13]
Hi Qiming,

In the CASSCF or CASCI objects, the main calculational method in the class (e.g. casci() or mc1step()) has an optional argument mo_coeff. If a user specifies something there when calling the object, in the current version, the user-specified value is not stored in the object. Is this an intentional design? I want to clarify this first with you, because from the README, you have certain guidelines on the OO interface. Is it not better to store that value if the user specifies something not None--which means he/she overrides the object's default initial mo_coeff?

Wirawan

**Comment by sunqm** [comment]
Hi Wirawan,

Currently, CASSCF.mc1step or CASCI.casci overwrite the default initial guess by the given one. Though, It's slightly agianst the coding rule (that the function without "_" suffix should be pure).  I think the overwritten of initial guess should be fine, since up to now this object is not exposed anywhere (there is no serialization during the iteration, the chkfile part only save the updated mo_coeff, not the entire object) until the return statement is reached.

Since the API is still in change, let's keep this issue alive to see what's going on for the API.

Best,
Qiming

**Comment by sunqm** [comment]
They are saved in the CASCI/CASSCF object since pyscf 1.0
