### ISSUE TITLE
pyscf1.4 : spin_square in dmrgci.py is missing

### ISSUE THREAD

**Issue by vamshimohank** [sunqm/pyscf#138]
I am trying to run dmrgscf examples for state averaged calculation. example 10-state_average.py in dmrgscf examples. It looks like spin_square module is removed from the dmrgci.py in version 1.4 and one gets an error "AttributeError: 'DMRGCI' object has no attribute 'spin_square'"

Wondering if its purposely done or a mistake is occurred somehow.  

Regards
Vamshi

**Comment by sunqm** [comment]
Block code does not provide a function to calculate the S^2 value.  In the spin-adapted block code, S^2 is good quantum number and in the early implementation, I directly output the S^2 value without calling block code.  Block also supports to run non-spin-adapted calculation.  The old implementation may output wrong S^2 value.  To avoid confusion, I deleted the relevant code but forgot to update the MCSCF interface.  The interface bug has been fixed in the latest commit.
