### ISSUE TITLE
CMakeLists.txt missing?

### ISSUE THREAD

**Issue by knarrff** [sunqm/pyscf#14]
The tutorial (http://sunqm.github.io/pyscf/tutorial.html#quick-setup) mentiones
```
git clone https://github.com/sunqm/pyscf
$ cd pyscf/lib
$ mkdir build
$ cd build
$ cmake ..
```
However, because pyscf is missing a CMakeLists.txt file, following this all you get is
```
CMake Error: The source directory "PATH/pyscf" does not appear to contain CMakeLists.txt.
```

**Comment by knarrff** [comment]
This did work for me - but I am not sure if this is the intended way. If it is, just the tutorial needs to be corrected.
```
cmake ../lib
```

**Comment by sunqm** [comment]
I'm not quite sure whether it's associated to your environment setting.  "PATH/pyscf" looks really strange because if the CMakeLists.txt is missed, the error message should be something like 
   The source directory "/home/sunqm/workspace" does not appear to contain CMakeLists.txt.

You can of cause do "cmake ../lib" if your build directory is under pyscf instead of  "pyscf/lib".

**Comment by knarrff** [comment]
Well, the message does say that - I just replaced the long path I have here with 'PATH'. What happened is that I missed the 'lib' part in the tutorial and just did a 'cd' into pyscf. Sorry for the noise. :-/
