### ISSUE TITLE
Package directory organization

### ISSUE THREAD

**Issue by azag0** [sunqm/pyscf#54]
Hi, great work, just found it via the arxiv preprint.

Would you be willing to consider restructuring the package along [more conventional lines](http://docs.python-guide.org/en/latest/writing/structure/)? That is, putting the top-level Python packages `/<package>` (such as `/scf`) into `/pyscf/<package>`. That way, the import path would be independent of how one names the containing directory and the note "DO NOT put pyscf in the path." would not be needed. The top level would then contain directories `pyscf`, `lib`, `doc`, and `examples`. The python files from `/lib` would be moved to `/pyscf/lib` and `/lib` would then contain only the C extensions.

**Comment by sunqm** [comment]
Good suggestion.  I'll change to this structure step by step in future release.

In release 1.3,  I'll add /pyscf directory at top-level to mimic the /<package>.  All top-level packages are symbolically linked to /pyscf.

In release 1.4,  top-level packages will be moved to /pyscf.  Symbolic linked modules will be placed at top level.  This layout will be kept in the following 1.* release for backward compatibility.

In release 2, the symbolic linked modules will be removed.

**Comment by azag0** [comment]
Great approach. I hope to find some time to get more familiar with pyscf.

**Comment by babbush** [comment]
I also suggest that you change the name of the folder "future". There is a popular python package called "future" (see http://python-future.org/) which is used to ensure that code is compatible with both python2 and python3. If pyscf is installed using your instructions (and the inner pyscf folder is added to the python path) then this messes up the future package. For instance, if I write "from future import *", it now imports things from your future folder instead of the python future package.

One can fix this by adding the directory that contains the top level pyscf folder to the python path instead of adding the top level pyscf folder to the python path. But that's also not a great solution because this might add other things I don't want to my python path.

**Comment by sunqm** [comment]
In the future 1.x release, modules will be moved out of the "future" directory.  But I'll keep this directory probably in whole 1.x versions, for backward compatibility.  I'll raise a warning message in future release if people try to import pyscf.future module.

**Comment by jarrodmcc** [comment]
Referencing what was said above, the current installation instructions add everything in the pyscf directory to the path rather than encapsulating it in the pyscf namespace.  One should rather add the folder containing pyscf to the Pythonpath variable, and add an extra insulating folder so as not to incidentally add any extra packages. 

That is, right now it recommends (if pyscf is install in /opt/pyscf) including /opt/pyscf.  This pollutes the namespace and breaks any packages which reference packages with names of the folder (e.g. future, tools, cc, scf etc).  One should rather add a buffer folder so that pyscf is installed in /opt/pyscf/pyscf, then add /opt/pyscf to the path.  This fixes the namespace pollution and prevents other packages in opt from accidentally being added.

Following the directions as given right now verbatim tends to break many other installed python packages, which is undesirable.

**Comment by azag0** [comment]
The planned reorganization will make the project conform to the standard. In the transition period, it is not ideal, but it's only temporary.

The problem with polluting the namespace can be simply solved by installing the Pyscf as a Pip [editable package](https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs) (which is in general a good approach for development). Instead of adding `/opt/pyscf` to `PYTHONPATH`, run

```
pip install -e /opt/pyscf
```

This automatically adds `/opt/pyscf` at the end of `sys.path`, ensuring that no built-in modules are shadowed by Pyscf.
